### ISSUE TITLE
Update all links to join form to go to meshforms

### ISSUE THREAD

**Issue by WillNilges** [nycmeshnet/meshforms#41]
Update the wiki to point to us instead of the old form
- [ ] Wiki
- [x] Website
- [ ] ???

**Comment by WillNilges** [comment]
This is like, _the last_ thing to do: Update all links to go to meshforms.

**Comment by Andrew-Dickinson** [comment]
Created a PR here for when the time is right: https://github.com/nycmeshnet/nycmesh.net/pull/154

I think this is all that is needed, fortunately, since all the links all go to `nycmesh.net/join` first, before sending the user to the Google Form with an extra link click. This is not optimal from a UX perspective but is currently the strategy for i18n, and perhaps let's not rock that boat until after launch

**Comment by LydonThorpe** [comment]
Updated PR to do this https://github.com/nycmeshnet/nycmesh.net/pull/163
